[build]
  # 构建命令
  command = "npm run build"
  # 发布目录
  publish = "public"
  # 函数目录
  functions = "netlify/functions"

[build.environment]
  # Node.js 版本
  NODE_VERSION = "18"
  # NPM 版本
  NPM_VERSION = "9"
  # 只安装生产依赖
  NODE_ENV = "production"
  # 跳过puppeteer下载
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
  # 加速npm安装
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_FUND = "false"

# 重定向规则 - SPA路由支持
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 头部设置
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 函数配置
[functions]
  # 函数目录已在 build.functions 中定义
  # 单个函数的超时和内存配置需要在各自的函数文件中定义

# 开发服务器设置
[dev]
  command = "npm run dev"
  port = 888
  publish = "public"
  functions = "netlify/functions"
